version: "3.9"

services:
  frontend:
    build: .
    image: monorepo-sandbox-frontend
    container_name: monorepo-sandbox-frontend
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    ports:
      - 3000:3000
