[tasks.docker-run]
description = "Run a command in Docker"
script = '''
cd docker
docker compose run --rm app sh -c "${@}"
'''

[tasks.serve]
script = '''
cd docker
docker compose up --build
'''

[tasks.down]
script = '''
cd docker
docker compose down
'''

[tasks.lint]
command = "makers"
args = [
  "docker-run",
  "cargo clippy --all-targets --all-features -- -D warnings",
]

[tasks.format]
command = "makers"
args = ["docker-run", "cargo fmt --all --check"]

[tasks.test]
command = "makers"
args = ["docker-run", "cargo nextest run"]

[tasks.db-connect]
script = '''
cd docker
docker exec -it slack-clone-db psql -U postgres
'''

[tasks.db-drop]
command = "makers"
args = ["docker-run", "sqlx db drop"]

[tasks.migrate-add]
command = "makers"
args = ["docker-run", "sqlx migrate add '${@}'"]

[tasks.migrate-run]
command = "makers"
args = ["docker-run", "sqlx db setup"]
