version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: slack-clone-app
    container_name: slack-clone-app
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ../..
        target: /app
      - type: volume
        source: slack-clone-app-cargo
        target: /usr/local/cargo/registry
      - type: volume
        source: slack-clone-app-target
        target: /app/target
    working_dir: /app/backend
    command: sh -c "cargo watch -x run"
    depends_on:
      - db
  db:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
      target: database
    image: slack-clone-db
    container_name: slack-clone-db
    ports:
      - 5432:5432
    volumes:
      - slack-clone-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slack_clone
    restart: always

volumes:
  slack-clone-app-cargo:
  slack-clone-app-target:
  slack-clone-pgdata:
