version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ..
        target: /app
      - type: volume
        source: app-cargo
        target: /usr/local/cargo/registry
      - type: volume
        source: app-target
        target: /app/target
    command: sh -c "cargo watch -x run"
  db:
    container_name: db
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
      target: database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slack-clone
    restart: always

volumes:
  app-cargo:
  app-target:
  pgdata:
