version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: notion-clone-app
    container_name: notion-clone-app
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ../..
        target: /app
      - type: volume
        source: notion-clone-app-cargo
        target: /usr/local/cargo/registry
      - type: volume
        source: notion-clone-app-target
        target: /app/target
    working_dir: /app/backend
    env_file: "${ENV_FILE:-../.env.dev}"
    command: "${COMMAND}"
    depends_on:
      - db
  db:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
      target: database
    image: notion-clone-db
    container_name: notion-clone-db
    ports:
      - 5432:5432
    volumes:
      - notion-clone-pgdata:/var/lib/postgresql/data
    restart: always
    env_file: "${ENV_FILE:-../.env.dev}"

volumes:
  notion-clone-app-cargo:
  notion-clone-app-target:
  notion-clone-pgdata:
