name: Frontend CI

on: [push, pull_request]

defaults:
  run:
    working-directory: ./frontend

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: ./.github/actions/pnpm-cache
      - name: Install dependencies
        run: pnpm install
      - name: Check
        run: pnpm tsc
