name: Infrastructure CI

on:
  push:
    paths:
      - .github/**
      - infrastructure/**
  pull_request:
    paths:
      - .github/**
      - infrastructure/**

defaults:
  run:
    working-directory: ./infrastructure/cdk/notion-clone

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Check
        run: pnpm tsc

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
